### ISSUE TITLE
Question about build

### ISSUE THREAD

**Issue by imrd1123** [whoenig/uav_trajectories#11]
Environment：
OS = Ubuntu 20.04
ROS = Noetic
Python = 3.8.10

---

Hello. I have a question about the build.
I execute the following command.
```
sudo apt install libnlopt-dev libgoogle-glog-dev
git clone --recursive https://github.com/whoenig/uav_trajectories.git
mkdir uav_trajectories/build
cd uav_trajectories/build
cmake .. 
make
```
but I get the following error and cannot proceed.
Is the `uav_trajectory` only available for Ubuntu 16.04?
Also, if you don't mind, could you please point out what I am doing wrong?

---

Error message 1
I got this when I first ran `make`.
![2021-11-11_004615](https://user-images.githubusercontent.com/9507900/141149118-a2cadf82-a7cb-4932-9e11-cf9e9be7084f.png)

Error message 2
I build `nlopt.hpp` which the cause of the error, separately and add `uav_trajectories/mav_trajectory_generation/mav_trajectory_generation/include/mav_trajectory_generation/` directory.
After that, I ran `make` and the following message came up.
![2021-11-11_005429](https://user-images.githubusercontent.com/9507900/141149536-2cddc004-d963-4594-bb97-6d2af453dd19.png)
![2021-11-11_005450](https://user-images.githubusercontent.com/9507900/141149553-275ae019-77b6-443d-8396-1bd44d7de135.png)
![2021-11-11_005503](https://user-images.githubusercontent.com/9507900/141149567-ed56a3e6-262d-42bb-ac40-42557d02013f.png)

**Comment by whoenig** [comment]
It's not finding `nlopt.hpp` on your system. What do you mean by "I build nlopt.hpp"?

**Comment by imrd1123** [comment]
Sorry for the confusing explanation.
In the first error, I got a message that `nlopt.hpp` was not found, 
so I downloaded it from the official nlopt page and built it separately. 
(from [https://github.com/stevengj/nlopt])
Then I moved the generated `nlopt.hpp` to the following directory.
`uav_trajectories/mav_trajectory_generation/mav_trajectory_generation/include/mav_trajectory_generation/`

In addition, changed the description in line 25 of `polynomial_optimization_nonlinear.h` from `#include <nlopt.hpp>` to `#include "nlopt.hpp"`. 
Then, I ran `make` again.

**Comment by imrd1123** [comment]
I solved the problem myself.
I was able to install `uav-trajectory` correctly by re-installing `libnlopt-dev,` `libgoogle-glog-dev` again, and rebuilding the `nlopt.hpp` file and placing it in bin/include.
Thanks for helping me.

**Comment by whoenig** [comment]
Thanks for the feedback~
