### ISSUE TITLE
CMake Issue - nlopt.hpp

### ISSUE THREAD

**Issue by uhvardhan** [whoenig/uav_trajectories#12]
`[ 80%] Built target mav_trajectory_generation
[ 90%] Building CXX object CMakeFiles/genTrajectory.dir/src/genTrajectory.cpp.o
In file included from /home/smartlab/Desktop/github_files/uav_trajectories/src/genTrajectory.cpp:8:
/home/smartlab/Desktop/github_files/uav_trajectories/mav_trajectory_generation/mav_trajectory_generation/include/mav_trajectory_generation/polynomial_optimization_nonlinear.h:25:10: fatal error: nlopt.hpp: No such file or directory
   25 | #include <nlopt.hpp>
      |          ^~~~~~~~~~~
compilation terminated.
make[2]: *** [CMakeFiles/genTrajectory.dir/build.make:63: CMakeFiles/genTrajectory.dir/src/genTrajectory.cpp.o] Error 1
make[1]: *** [CMakeFiles/Makefile2:78: CMakeFiles/genTrajectory.dir/all] Error 2
make: *** [Makefile:84: all] Error 2
`

I am running Ubuntu 20.04.

**Comment by whoenig** [comment]
See https://github.com/whoenig/uav_trajectories/issues/11#issuecomment-972468323

I am leaving this issue open in order to improve the documentation and to add CI.

**Comment by uhvardhan** [comment]
Thank you. I am going to work on it now

Can I help you with adding it to the documentation maybe? Let me know.

**Comment by whoenig** [comment]
Should be fixed in the latest version (documentation, code fixes, CI for Ubuntu 20.04). Let me know if it doesn't work for you.
