### ISSUE TITLE
Drone swarm formation path-planning for collision avoidance.

### ISSUE THREAD

**Issue by raghavsuri13** [whoenig/uav_trajectories#17]
Hi, 

I'm working on a project that involves a large number of drones that are supposed to takeoff from an initial grid, and create a set of formations one after another, at the end of which the drones land at their initial starting positions, how can I use this to plan the trajectories for each of the drones in the formation such that collision avoidance is guaranteed. There are no static obstacles in the simulation, the only obstacles are the drones themselves. 

Thanks!
P.S. The number of drones may range from 100 - 5000.

**Comment by whoenig** [comment]
This repo is for single UAVs only. For your use case, I'd recommend Buffered Voronoi Cells or Control Barrier Functions.

**Comment by raghavsuri13** [comment]
Hi, thanks for the advice,
I'd also come across one of your research papers called "Trajectory Planning for Quadrotor Swarms". I believe that approach would be very apt for my use case considering we need to just preplan the paths for all the drones, we don't require real-time monitoring as the drones would potentially have no onboard sensors or cameras as well as no separate camera monitoring them. Could you suggest the correct approach for the same or would you suggest I go with Buffered Voronoi Cells / Control Barrier Functions. 
Thanks for the help!

**Comment by whoenig** [comment]
If you don't have any obstacles, then the paper you mentioned is overkill and BVC/CBF are the better choice.

**Comment by raghavsuri13** [comment]
Hi, 
Could I get in touch with you somewhere else privately, I have a few questions about the implementation and would need to explain the project that I'm working on as well. 
Again thanks a lot for all the help, I really appreciate it.

**Comment by whoenig** [comment]
You can find my contact info at https://whoenig.github.io/.

**Comment by raghavsuri13** [comment]
Perfect, I guess we can mark this issue closed.

**Comment by raghavsuri13** [comment]
Perfect, I guess we can mark this issue closed.
