### ISSUE TITLE
What is in waypoints1.csv?

### ISSUE THREAD

**Issue by abdul-mannan-khan** [whoenig/uav_trajectories#20]
Hello @whoenig , 

Thank you for creating this useful repository. I am trying to create waypoints for the drone. I am having difficulty understanding the `waypoints1.csv` file in the `example` folder. I see that there are three columns. The first column consists of zeros, and there are some numbers in the second and third columns. I am confused about what is in the second and third columns. I have gone through the previous isse [How to translate the trajectory I want to design into .csv format](https://github.com/whoenig/uav_trajectories/issues/4), particularly [this discussion](https://github.com/whoenig/uav_trajectories/issues/4#issuecomment-557334396). It seems that  I just need to provide some x,y,z coordinates. However, I am confused about which column represents `x`, `y` and `z`. From the visualization is that first column is `x`, second column is `y` and third column is `z`. Please correct me if I am wrong. Thank you so much for your response.

**Comment by whoenig** [comment]
You are correct. The columns are x, y, z and the rows are the waypoints. `genTrajectory` is going to find a smooth spline that connects these waypoints as well as the total time (based on your velocity and acceleration limits). Use the visualization script to visualize position and derivatives.
