### ISSUE TITLE
Help in generating the trajectory in run time based on getting target points and obstacles around 

### ISSUE THREAD

**Issue by abdul-mannan-khan** [whoenig/uav_trajectories#21]
Hello, 

This is a great repository and very helpful. Thank you so much for making it public. I need help in using this repository to generate trajectory in runtime and not pre-programmed flight paths. Basically, I would like to extract information about target points from sensors along with obstacles along the way, and I need help utilizing this repository to generate the trajectory within the code. I tried to study `[generate_trajectory.py](https://github.com/whoenig/uav_trajectories/blob/main/scripts/generate_trajectory.py)`, but I guess it requires waypoints. Also, my code is in Python. Thank you for your guidance.

**Comment by whoenig** [comment]
This repository will not be in particular useful for this task, unfortunately. It has no notions of obstacles.
