### ISSUE TITLE
Time allocation in trajectory design

### ISSUE THREAD

**Issue by Allenhanbo** [whoenig/uav_trajectories#6]
Hi Whoenig, when I was looking source code of genTrajectory.cpp. I found that the time allocation of each segment you choose is 6.5: https://github.com/whoenig/uav_trajectories/blob/278d92db0f0244edf149efdb89d6e03e7f3c057b/src/genTrajectory.cpp#L109

Can I ask how you get this "magic" time allocation?

**Comment by whoenig** [comment]
I just took it from the examples in https://github.com/ethz-asl/mav_trajectory_generation (my repository is really just a simpler-to-use wrapper around that code.) Perhaps you can find some help over there.
